apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gj1uenq57-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:35556ed6ba4398844590c26a5873fb0d65cb3bb7@sha256:3542a93c2ff27b0da3b03f9c0bb37441d2bc2755b0f96bc6d0c3a35cfebf1678
          name: container-image
